name: Update databases
run-name: Update databases
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'  # Runs every day at 8pm JST
jobs:
  Update-db:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Update database
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python update_db.py
      - name: Commit files
        env:
          github_token: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated databases" && true)
          git push origin main